insert into public.user (name, post_code, profession) values ('Forkan', null, 'Environmental Tech');
insert into public.user (name, post_code, profession) values ('Solomonides', '34230', 'Speech Pathologist');
insert into public.user (name, post_code, profession) values ('Hapke', '241551', 'Information Systems Manager');
insert into public.user (name, post_code, profession) values ('Jemison', null, 'Executive Secretary');
insert into public.user (name, post_code, profession) values ('Shadfourth', '83-047', 'Geologist III');
insert into public.user (name, post_code, profession) values ('Rockwill', null, 'Budget/Accounting Analyst I');
insert into public.user (name, post_code, profession) values ('Stiffkins', null, 'Chemical Engineer');
insert into public.user (name, post_code, profession) values ('Stollard', null, 'VP Product Management');
insert into public.user (name, post_code, profession) values ('Eye', null, 'Design Engineer');
insert into public.user (name, post_code, profession) values ( 'Smalls', '92154 CEDEX', 'Administrative Assistant III');
insert into public.user (name, post_code, profession) values ( 'Lamb', '4950-081', 'Human Resources Manager');
insert into public.user (name, post_code, profession) values ( 'McCloy', null, 'Staff Accountant IV');
insert into public.user (name, post_code, profession) values ( 'Clench', null, 'Environmental Specialist');
insert into public.user (name, post_code, profession) values ( 'Kinnach', null, 'Professor');
insert into public.user (name, post_code, profession) values ( 'Pye', '413-0033', 'Associate Professor');
insert into public.user (name, post_code, profession) values ( 'Jarrette', null, 'Food Chemist');
insert into public.user (name, post_code, profession) values ( 'Fernehough', 'P0T', 'Quality Control Specialist');
insert into public.user (name, post_code, profession) values ( 'Beccera', null, 'Teacher');
insert into public.user (name, post_code, profession) values ( 'Bourke', '33450', 'Programmer Analyst II');
insert into public.user (name, post_code, profession) values ( 'Robbert', null, 'Marketing Manager');
insert into public.user (name, post_code, profession) values ( 'Norree', null, 'Project Manager');
insert into public.user (name, post_code, profession) values ( 'Havelin', '09-450', 'Senior Sales Associate');
insert into public.user (name, post_code, profession) values ( 'Airey', null, 'Biostatistician I');
insert into public.user (name, post_code, profession) values ( 'Philipart', '3070-085', 'Food Chemist');
insert into public.user (name, post_code, profession) values ( 'Temlett', null, 'Programmer Analyst IV');
insert into public.user (name, post_code, profession) values ( 'Thoday', null, 'Clinical Specialist');
insert into public.user (name, post_code, profession) values ( 'Yakhin', '436 03', 'Senior Editor');
insert into public.user (name, post_code, profession) values ( 'Worsnap', '901 86', 'Cost Accountant');
insert into public.user (name, post_code, profession) values ( 'Langlois', null, 'VP Accounting');
insert into public.user (name, post_code, profession) values ( 'Beardsworth', '2550', 'Software Consultant');
insert into public.user (name, post_code, profession) values ( 'Elcome', '3249', 'Teacher');
insert into public.user (name, post_code, profession) values ( 'Arend', null, 'General Manager');
insert into public.user (name, post_code, profession) values ( 'Hoston', null, 'Statistician IV');
insert into public.user (name, post_code, profession) values ( 'Crichmer', '26-806', 'Desktop Support Technician');
insert into public.user (name, post_code, profession) values ( 'Sandells', null, 'Information Systems Manager');
insert into public.user (name, post_code, profession) values ( 'Coatts', null, 'GIS Technical Architect');
insert into public.user (name, post_code, profession) values ( 'Newman', null, 'Product Engineer');
insert into public.user (name, post_code, profession) values ( 'Collinge', null, 'Health Coach III');
insert into public.user (name, post_code, profession) values ( 'Baudts', '85423-000', 'Programmer Analyst I');
insert into public.user (name, post_code, profession) values ( 'Bartul', '94140', 'Project Manager');
insert into public.user (name, post_code, profession) values ( 'Abbatt', null, 'Community Outreach Specialist');
insert into public.user (name, post_code, profession) values ( 'Tremblot', null, 'Administrative Officer');
insert into public.user (name, post_code, profession) values ( 'Rosendahl', '53000-000', 'Geologist III');
insert into public.user (name, post_code, profession) values ( 'Paulet', null, 'Food Chemist');
insert into public.user (name, post_code, profession) values ( 'Haselgrove', null, 'Occupational Therapist');
insert into public.user (name, post_code, profession) values ( 'Narup', '3636', 'Marketing Manager');
insert into public.user (name, post_code, profession) values ( 'MacCumiskey', null, 'Senior Cost Accountant');
insert into public.user (name, post_code, profession) values ( 'Lemanu', null, 'Automation Specialist IV');
insert into public.user (name, post_code, profession) values ( 'Lindenbluth', null, 'Product Engineer');
insert into public.user (name, post_code, profession) values ( 'Bediss', '49140-000', 'Structural Analysis Engineer');
