insert into public.user (id, name, post_code, profession) values (1, 'Forkan', null, 'Environmental Tech');
insert into public.user (id, name, post_code, profession) values (2, 'Solomonides', '34230', 'Speech Pathologist');
insert into public.user (id, name, post_code, profession) values (3, 'Hapke', '241551', 'Information Systems Manager');
insert into public.user (id, name, post_code, profession) values (4, 'Jemison', null, 'Executive Secretary');
insert into public.user (id, name, post_code, profession) values (5, 'Shadfourth', '83-047', 'Geologist III');
insert into public.user (id, name, post_code, profession) values (6, 'Rockwill', null, 'Budget/Accounting Analyst I');
insert into public.user (id, name, post_code, profession) values (7, 'Stiffkins', null, 'Chemical Engineer');
insert into public.user (id, name, post_code, profession) values (8, 'Stollard', null, 'VP Product Management');
insert into public.user (id, name, post_code, profession) values (9, 'Eye', null, 'Design Engineer');
insert into public.user (id, name, post_code, profession) values (10, 'Smalls', '92154 CEDEX', 'Administrative Assistant III');
insert into public.user (id, name, post_code, profession) values (11, 'Lamb', '4950-081', 'Human Resources Manager');
insert into public.user (id, name, post_code, profession) values (12, 'McCloy', null, 'Staff Accountant IV');
insert into public.user (id, name, post_code, profession) values (13, 'Clench', null, 'Environmental Specialist');
insert into public.user (id, name, post_code, profession) values (14, 'Kinnach', null, 'Professor');
insert into public.user (id, name, post_code, profession) values (15, 'Pye', '413-0033', 'Associate Professor');
insert into public.user (id, name, post_code, profession) values (16, 'Jarrette', null, 'Food Chemist');
insert into public.user (id, name, post_code, profession) values (17, 'Fernehough', 'P0T', 'Quality Control Specialist');
insert into public.user (id, name, post_code, profession) values (18, 'Beccera', null, 'Teacher');
insert into public.user (id, name, post_code, profession) values (19, 'Bourke', '33450', 'Programmer Analyst II');
insert into public.user (id, name, post_code, profession) values (20, 'Robbert', null, 'Marketing Manager');
insert into public.user (id, name, post_code, profession) values (21, 'Norree', null, 'Project Manager');
insert into public.user (id, name, post_code, profession) values (22, 'Havelin', '09-450', 'Senior Sales Associate');
insert into public.user (id, name, post_code, profession) values (23, 'Airey', null, 'Biostatistician I');
insert into public.user (id, name, post_code, profession) values (24, 'Philipart', '3070-085', 'Food Chemist');
insert into public.user (id, name, post_code, profession) values (25, 'Temlett', null, 'Programmer Analyst IV');
insert into public.user (id, name, post_code, profession) values (26, 'Thoday', null, 'Clinical Specialist');
insert into public.user (id, name, post_code, profession) values (27, 'Yakhin', '436 03', 'Senior Editor');
insert into public.user (id, name, post_code, profession) values (28, 'Worsnap', '901 86', 'Cost Accountant');
insert into public.user (id, name, post_code, profession) values (29, 'Langlois', null, 'VP Accounting');
insert into public.user (id, name, post_code, profession) values (30, 'Beardsworth', '2550', 'Software Consultant');
insert into public.user (id, name, post_code, profession) values (31, 'Elcome', '3249', 'Teacher');
insert into public.user (id, name, post_code, profession) values (32, 'Arend', null, 'General Manager');
insert into public.user (id, name, post_code, profession) values (33, 'Hoston', null, 'Statistician IV');
insert into public.user (id, name, post_code, profession) values (34, 'Crichmer', '26-806', 'Desktop Support Technician');
insert into public.user (id, name, post_code, profession) values (35, 'Sandells', null, 'Information Systems Manager');
insert into public.user (id, name, post_code, profession) values (36, 'Coatts', null, 'GIS Technical Architect');
insert into public.user (id, name, post_code, profession) values (37, 'Newman', null, 'Product Engineer');
insert into public.user (id, name, post_code, profession) values (38, 'Collinge', null, 'Health Coach III');
insert into public.user (id, name, post_code, profession) values (39, 'Baudts', '85423-000', 'Programmer Analyst I');
insert into public.user (id, name, post_code, profession) values (40, 'Bartul', '94140', 'Project Manager');
insert into public.user (id, name, post_code, profession) values (41, 'Abbatt', null, 'Community Outreach Specialist');
insert into public.user (id, name, post_code, profession) values (42, 'Tremblot', null, 'Administrative Officer');
insert into public.user (id, name, post_code, profession) values (43, 'Rosendahl', '53000-000', 'Geologist III');
insert into public.user (id, name, post_code, profession) values (44, 'Paulet', null, 'Food Chemist');
insert into public.user (id, name, post_code, profession) values (45, 'Haselgrove', null, 'Occupational Therapist');
insert into public.user (id, name, post_code, profession) values (46, 'Narup', '3636', 'Marketing Manager');
insert into public.user (id, name, post_code, profession) values (47, 'MacCumiskey', null, 'Senior Cost Accountant');
insert into public.user (id, name, post_code, profession) values (48, 'Lemanu', null, 'Automation Specialist IV');
insert into public.user (id, name, post_code, profession) values (49, 'Lindenbluth', null, 'Product Engineer');
insert into public.user (id, name, post_code, profession) values (50, 'Bediss', '49140-000', 'Structural Analysis Engineer');
